greeting1 = Greeting.create(message: "Hello from the other side 1")
greeting2 = Greeting.create(message: "Hello from the other side 2")
greeting3 = Greeting.create(message: "Hello from the other side 3")
greeting4 = Greeting.create(message: "Hello from the other side 4")
greeting5 = Greeting.create(message: "Hello from the other side 5")